### ISSUE TITLE
Typescript types for PatchRequestBody are wrong

### ISSUE THREAD

**Issue by Inrixia** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#31]
Hi,

According to the SDK Types the PatchRquestBody (line 2131) supports operations in a object and directly. 
This appears to be incorrect in practise.
`node_modules\@azure\cosmos\dist\types\latest\cosmos.d.ts@2131`
```ts
export declare type PatchRequestBody = {
    operations: PatchOperation[];
    condition?: string;
} | PatchOperation[];
```

When patchRequestBody is an array of operations I receive the following error:
```
Error: Bulk request errored with: Message: {"Errors":["Field 'resourceBody' has unexpected value type."]}
ActivityId: dddfc6e8-7ebd-46da-a11a-96702ecaecb6, Request URI: /apps/01131d1b-88b5-4c5a-a422-888fed6df2ca/services/59e5dec8-d9c9-4509-9fa8-f24c37f503bb/partitions/37217991-f208-4439-9882-acbbb74b70e3/replicas/132738345581654848p/, RequestStats:
RequestStartTime: 2021-11-18T04:53:59.5603273Z, RequestEndTime: 2021-11-18T04:53:59.5699759Z,  Number of regions attempted:1
{"systemHistory":[{"dateUtc":"2021-11-18T04:53:02.3878238Z","cpu":4.602,"memory":37034037248.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0151,"availableThreads":32763,"minThreads":24,"maxThreads":32767}},{"dateUtc":"2021-11-18T04:53:12.3982103Z","cpu":5.990,"memory":37203009536.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0173,"availableThreads":32765,"minThreads":24,"maxThreads":32767}},{"dateUtc":"2021-11-18T04:53:22.4085911Z","cpu":4.421,"memory":37266087936.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0408,"availableThreads":32764,"minThreads":24,"maxThreads":32767}},{"dateUtc":"2021-11-18T04:53:32.4189507Z","cpu":4.712,"memory":37571575808.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0195,"availableThreads":32765,"minThreads":24,"maxThreads":32767}},{"dateUtc":"2021-11-18T04:53:42.4293545Z","cpu":12.421,"memory":38053511168.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0261,"availableThreads":32764,"minThreads":24,"maxThreads":32767}},{"dateUtc":"2021-11-18T04:53:52.4397309Z","cpu":16.407,"memory":38582865920.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0259,"availableThreads":32759,"minThreads":24,"maxThreads":32767}}]}
RequestStart: 2021-11-18T04:53:59.5603273Z; ResponseTime: 2021-11-18T04:53:59.5699759Z; StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-australiaeast1-fd16.documents.azure.com:14069/apps/01131d1b-88b5-4c5a-a422-888fed6df2ca/services/59e5dec8-d9c9-4509-9fa8-f24c37f503bb/partitions/37217991-f208-4439-9882-acbbb74b70e3/replicas/132738345581654848p/, LSN: 90577919, GlobalCommittedLsn: 90577919, PartitionKeyRangeId: , IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: -1#90577919, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.224, ActivityId: dddfc6e8-7ebd-46da-a11a-96702ecaecb6, TransportRequestTimeline: {"requestTimeline":[{"event": "Created", "startTimeUtc": "2021-11-18T04:53:59.5603273Z", "durationInMs": 0.0133},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2021-11-18T04:53:59.5603406Z", "durationInMs": 0.0116},{"event": "Pipelined", "startTimeUtc": "2021-11-18T04:53:59.5603522Z", "durationInMs": 0.1372},{"event": "Transit Time", "startTimeUtc": "2021-11-18T04:53:59.5604894Z", "durationInMs": 4.9625},{"event": "Received", "startTimeUtc": "2021-11-18T04:53:59.5654519Z", "durationInMs": 0.0778},{"event": "Completed", "startTimeUtc": "2021-11-18T04:53:59.5655297Z", "durationInMs": 0}],"requestSizeInBytes":1022,"requestBodySizeInBytes":486,"responseMetadataSizeInBytes":166,"responseBodySizeInBytes":62};
 ResourceType: Document, OperationType: Batch
, SDK: Microsoft.Azure.Documents.Common/2.14.0
    at \node_modules\@azure\cosmos\dist\index.js:5506:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Items.bulk (\node_modules\@azure\cosmos\dist\index.js:5480:9)
    at async timeoutMultiplier (\dist\threads\cosmos.js:38:32)
    at async tryAgain (\node_modules\@inrixia\helpers\logic\index.js:34:20)
    at async Promise.all (index 0)
    at async Timeout.indexer [as _onTimeout] (\dist\threads\cosmos.js:37:13)
```

But when using the first type where operations is inside a object it works.

**Comment by Inrixia** [comment]
Adding some extra info...

This is for the Node.js `@azure/cosmos` sdk, I'm using version `3.14.1`

**Comment by sajeetharan** [comment]
@Inrixia can you open this issue on the https://github.com/Azure/azure-sdk-for-js/issues repository

**Comment by Inrixia** [comment]
> @Inrixia can you open this issue on the https://github.com/Azure/azure-sdk-for-js/issues repository

I haven't been using the library since this feature went out of preview so can't check if this is still a issue.
